=== bradik/masterjava/src/test/resources/payload_new.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" targetNamespace="http://javaops.ru" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="Payload">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Users">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="User" maxOccurs="unbounded" minOccurs="0">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="fullName">
                      <xs:simpleType>
                        <xs:restriction base="xs:string">
                          <xs:enumeration value="Full Name"/>
                          <xs:enumeration value="Admin"/>
                          <xs:enumeration value="Deleted"/>
                        </xs:restriction>
                      </xs:simpleType>
                    </xs:element>
                    <xs:element name="groupItem" maxOccurs="unbounded" minOccurs="0">
                      <xs:complexType>
                        <xs:simpleContent>
                          <xs:extension base="xs:string">
                            <xs:attribute type="xs:string" name="group" use="optional"/>
                          </xs:extension>
                        </xs:simpleContent>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                  <xs:attribute type="xs:string" name="flag" use="optional"/>
                  <xs:attribute type="xs:string" name="city" use="optional"/>
                  <xs:attribute type="xs:string" name="email" use="optional"/>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="Cities">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="City" maxOccurs="unbounded" minOccurs="0">
                <xs:complexType>
                  <xs:simpleContent>
                    <xs:extension base="xs:string">
                      <xs:attribute type="xs:string" name="id" use="optional"/>
                    </xs:extension>
                  </xs:simpleContent>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="Groups">
          <xs:complexType mixed="true">
            <xs:sequence>
              <xs:element name="Group" maxOccurs="unbounded" minOccurs="0">
                <xs:complexType>
                  <xs:simpleContent>
                    <xs:extension base="xs:string">
                      <xs:attribute type="xs:string" name="id" use="optional"/>
                      <xs:attribute type="xs:string" name="type" use="optional"/>
                      <xs:attribute type="xs:string" name="project" use="optional"/>
                    </xs:extension>
                  </xs:simpleContent>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="Projects">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="Project" maxOccurs="unbounded" minOccurs="0">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="Name">
                      <xs:simpleType>
                        <xs:restriction base="xs:string">
                          <xs:enumeration value="topjava"/>
                          <xs:enumeration value="masterjava"/>
                        </xs:restriction>
                      </xs:simpleType>
                    </xs:element>
                    <xs:element name="Description">
                      <xs:simpleType>
                        <xs:restriction base="xs:string">
                          <xs:enumeration value="Описание проекта topjava"/>
                          <xs:enumeration value="Описание проекта masterjava"/>
                        </xs:restriction>
                      </xs:simpleType>
                    </xs:element>
                  </xs:sequence>
                  <xs:attribute type="xs:string" name="id" use="optional"/>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== bradik/masterjava/src/main/resources/payload_new.xml
<Payload xmlns="http://javaops.ru"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://javaops.ru payload_new.xsd">

    <Cities>
        <City id="spb">Санкт-Петербург</City>
        <City id="kiv">Киев</City>
        <City id="mnsk">Минск</City>
    </Cities>
    <Projects>
        <Project name="topjava">
            <Description>Описание проекта: topjava</Description>
            <Group name="topjava06" type="FINISHED"/>
            <Group name="topjava07" type="FINISHED"/>
            <Group name="topjava08" type="CURRENT"/>
        </Project>
        <Project name="masterjava">
            <Description>Описание проекта masterjava</Description>
            <Group name="masterjava01" type="CURRENT"/>
        </Project>
    </Projects>
    <Users>
        <User flag="active" city="kiv" email="admin@javaops.ru" groupRefs="topjava06  topjava07 topjava08">Full Name
        </User>
        <User flag="superuser" city="spb" email="admin@javaops.ru" groupRefs="topjava08">Admin</User>
        <User flag="deleted" city="spb" email="mail@yandex.ru" groupRefs="masterjava01">Deleted</User>
    </Users>
</Payload>
